init:
  position:
    x: 0.69234593
    y: -1.39575202
    z: 312.2643980319930
    covx: 1.218469679146834e-14
    covy: 1.218469679146834e-14
    covz: 0.010000000000000
  ecef:
      x: 856206.8996
      y: -4841351.0969
      z: 4049888.7599
  bias:
    accel:
      x: 0.0
      y: 0.0
      z: 0.0
    gyro:
      x: 0.0
      y: 0.0
      z: 0.0
      
imu:
  publish_hz: 250
  sensor_pub_rate: 250
  topic: /imu/dataAdis

gps_llh:
    topic: /bestpos
gps_ecef:
    topic: /bestxyz

frames:
  frame_id_out: map
  frame_id_fixed: odom
  frame_id_imu: imu_link
  frame_id_odo: odom_link
