imu:
  publish_hz: 250
  sensor_pub_rate: 250
  topic: /imu/dataAdis

gps_llh:
    topic: /bestpos
gps_ecef:
    topic: /bestxyz

frames:
  frame_id_out: map
  frame_id_fixed: odom
  frame_id_imu: imu_link
  frame_id_odo: odom_link
